apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-pv
spec:
  # El valor "" (vacío) es crucial para ignorar la StorageClass local-path
  storageClassName: ""
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-pvc
spec:
  # Debe ser idéntico al del PV para que se vinculen
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  # Referencia directa al volumen que creamos arriba
  volumeName: {{ include "homeassistant.fullname" . }}-pv