apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-pv
spec:
  storageClassName: manual # Clase manual para evitar buscadores automáticos
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-pvc
spec:
  storageClassName: manual # Debe coincidir con el PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  # Forzamos a que busque este PV específico por nombre
  volumeName: {{ include "homeassistant.fullname" . }}-pv