apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homeassistant.fullname" . }}-pv
spec:
  # Cambiamos esto para que coincida con lo que el clúster espera
  storageClassName: local-path 
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homeassistant.fullname" . }}-pvc
spec:
  # Ahora ambos coinciden perfectamente
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ include "homeassistant.fullname" . }}-pv