apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv # Nombre estático para asegurar match
spec:
  storageClassName: "" # Esto deshabilita local-path en el PV
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
spec:
  storageClassName: "" # Esto deshabilita local-path en el PVC
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: homeassistant-pv # Apunta directamente al nombre del PV