apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homeassistant-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate  # <-- ESTO ROMPE EL BLOQUEO: vincula sin esperar al Pod
reclaimPolicy: Retain